 #设置语言
language: node_js  
# 指定需要sudo权限
sudo: required
#设置相应的版本
node_js: 
  - 7.9.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
    directories:
        - node_modules    
before_install:
  - npm install -g hexo-cli
#安装hexo及插件
install:
  - npm install   
  - npm install hexo-deployer-git --save
script:
  - hexo clean
  - hexo generate
#修改成自己的github用户名
#修改成自己的GitHub邮箱
#GH_token就是在travis中设置的token
after_script:
  - cd ./public
  - git init
  - git config user.name "iszengmh"   
  - git config user.email "iszengmh@qq.com"   
  - git add .
  - git commit -m "update by Travis-CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master 
 #只监测这个分支，一有动静就开始构建
branches:
  only:
  - blog 
env:
    global:
        - GH_REF: github.com/iszengmh/iszengmh.github.io.git